ProjektMOIS/Controllers/HomeController.cs
using ProjektMOIS.DAO;
using ProjektMOIS.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjektMOIS.Controllers
{
    public class HomeController : Controller
    {
        private ITripDAO tripDAO = new TripDAO();

        public ActionResult Index()
        {

            IList<Trip> trips = tripDAO.GetAllByCategory("Last Minute");

            ViewBag.Trips = trips;

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ProjektMOIS/Controllers/SearchController.cs
using ProjektMOIS.DAO;
using ProjektMOIS.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjektMOIS.Controllers
{
    public class SearchController : Controller
    {
        private ITripDAO tripDAO = new TripDAO();

        // GET: Search
        public ActionResult Index(string destination, int days, DateTime date, float prize)
        {

            IList<Trip> trips = tripDAO.GetByFilters(destination, days, date, prize);

            ViewBag.Trips = trips;

            return View();
        }

        // GET: Search/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Search/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Search/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Search/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Search/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Search/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Search/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ProjektMOIS/Controllers/TripController.cs
using ProjektMOIS.DAO;
using ProjektMOIS.Model;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ProjektMOIS.Controllers
{
    public class TripController : Controller 
    {
        private ITripDAO tripDAO = new TripDAO();

        // GET: Trip/5
        public ActionResult Index(long id)
        {
            Trip trip = tripDAO.GetById(id);

            ViewBag.Trip = trip;

            return View();
        }

        // GET: Trip/Register/5

        public ActionResult Register(long id)
        {
            Trip trip = tripDAO.GetById(id);

            ViewBag.Trip = trip;

            return View();
        }

        // GET: Trip/Create

        public ActionResult Create()
        {

            return View();
        }

    }
}

ProjektMOIS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ProjektMOIS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProjektMOIS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<hr>
<h1>Hledat</h1>
<header class="jumbotron hero-spacer">
    <div class="row">
        <div class="col-lg-12">
            <form action="/search" asp-area="" asp-controller="Search" asp-action="Index">
                <div class="col-md-3 col-sm-6">
                    <label>
                        Destinace:
                    </label>
                    <input type="text" class="form-control" value="Řecko" name="destination" />
                </div>
                <div class="col-md-3 col-sm-6">
                    <label>
                        Počet dní:
                    </label>
                    <input type="number" min="0" class="form-control" value="7" name="days" />
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="form-group">
                        <label>
                            Datum odjezdu
                        </label>
                        <input type="date" class="form-control" value="2017-04-13" name="date" />
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="form-group">
                        <label>
                            Maximální cena
                        </label>
                        <input type="number" class="form-control" value="7000" min="5000" step="500" name="prize" />
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 pull-right">
                    <div class="form-group">
                        <p>
                            <button class="btn btn-primary btn-large pull-right" type="submit">
                                <span class="glyphicon glyphicon-search" aria-hidden="true">
                                </span>&nbsp;Hledat
                            </button>
                        </p>
                    </div>
                </div>
            </form>
        </div>
    </div>
</header>
<hr>
<!-- Title -->
<div class="row">
    <div class="col-lg-12">
        <h3>Last minute</h3>
    </div>
</div>
<!-- /.row -->
<!-- Page Features -->
<div class="row text-center">

    @foreach (var t in ViewBag.Trips)
    {
        <div class="col-md-3 col-sm-6 hero-feature">
            <div class="thumbnail">
                <img src="/Content/beach.jpg" alt="">
                <div class="caption">
                    <h3>@t.Destination</h3>
                    <h4>                                                                                                                                                                    <b>20.4. - 28.4.2016</b>                                                                                                                                              </h4>
                    <p>
                        @t.Description
                    </p>
                    <p>
                        <b>Cena: @t.Prize ,- </b>
                    </p>
                    <p>
                        <a href="/trip/register?id=@t.Id" class="btn btn-primary">Registrovat</a>
                        <a href="/trip?id=@t.Id" class="btn btn-default">Více informací</a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>
<!-- /.row -->
<hr>

ProjektMOIS/Views/Search/Index.cshtml
@{
    ViewBag.Title = "Search";
}

<hr>
<h1>Výsledky hledání </h1>
<!-- Title -->
<div class="row">
    <div class="col-lg-12">
        <h3>Latest Features</h3>
    </div>
</div>
<!-- /.row -->
<!-- Page Features -->
<div class="row text-center">
    @foreach (var t in ViewBag.Trips)
    {
        <div class="col-md-3 col-sm-6 hero-feature">
            <div class="thumbnail">
                <img src="/Content/beach.jpg" alt="">
                <div class="caption">
                    <h3>@t.Destination</h3>
                    <h4>                                                                                                                                                                    <b>20.4. - 28.4.2016</b>                                                                                                                                              </h4>
                    <p>
                        @t.Description
                    </p>
                    <p>
                        <b>Cena: @t.Prize ,- </b>
                    </p>
                    <p>
                        <a href="/trip/register?id=@t.Id" class="btn btn-primary">Registrovat</a>
                        <a href="/trip?id=@t.Id" class="btn btn-default">Více informací</a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>
<!-- /.row -->
<hr>

ProjektMOIS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectMOIS</title>

    <link href="/Content/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="/Content/heroic-features.css" rel="stylesheet">


    <link href="/Content/ourcss.css" rel="stylesheet">   
</head>
<body>
    <nav class="navbar navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">
                        Toggle navigation
                    </span>
                    <span class="icon-bar">
                    </span>
                    <span class="icon-bar">
                    </span>
                    <span class="icon-bar">
                    </span>
                </button>
                <a class="navbar-brand" href="/" asp-area="" asp-controller="Home" asp-action="Index">BLUE TRAVEL</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/" asp-area="" asp-controller="Home" asp-action="Index">Vyhledávání</a>
                    </li>
                    <li>
                        <a href="/trip" asp-area="" asp-controller="Trip" asp-action="Index">Akční hity</a>
                    </li>
                    <li>
                        <a href="/home/contact"  asp-area="" asp-controller="Home" asp-action="Contact">Kontakty</a>
                    </li>
                    <li>
                        <a href="/home/about" asp-area="" asp-controller="Home" asp-action="About">O nás</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>  
    <div class="container body-content">
        @RenderBody()
        <hr />        
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>
                        Copyright &copy; UHK, MOIS 2017
                    </p>
                </div>
            </div>
        </footer>   
    </div>



    @RenderSection("Scripts", required: false)
</body>
</html>

ProjektMOIS/Views/Trip/Create.cshtml
@{
    ViewBag.Title = "About";
}

<hr>
<h1>Nový zájezd</h1>

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="form-group">
            <label class="control-label">
                Název zájezdu
            </label>
            <input class="form-control" type="text" value="" placeholder="Dovolená pro rodinu v Řecku" />
        </div>
    </div>
    <div class="panel-body">

        <div class="form-container">

            <div class="form-group">
                <label class="control-label">
                    Typ zájezdu
                </label>
                <select class="form-control">
                    <option>Pobytové zájezdy</option>
                    <option>Blízká moře</option>
                    <option>Lyžařské zájezdy</option>
                    <option>Poznávací zájezdy</option>
                    <option>...</option>
                </select>

            </div>

            <div class="form-group">
                <label class="control-label">
                    Cílová země
                </label>
                <input class="form-control" type="text" placeholder="Řecko" />
            </div>


            <div class="form-group">
                <label class="control-label">
                    Délka (dny)
                </label>
                <input class="form-control" type="number" value="5" min="0" />
            </div>


            <div class="form-group">
                <label class="control-label">
                    Typ dopravy
                </label>
                <select class="form-control">
                    <option>Autobusem</option>
                    <option>Letadlem</option>
                    <option>...</option>
                </select>
            </div>


            <div class="form-group">
                <label class="control-label">
                    Cena
                </label>
                <input class="form-control" type="number" value="5000" min="5000" step="500" />
            </div>

            <div class="form-group">
                <label class="control-label">
                    Kategorie
                </label>
                <select class="form-control">
                    <option>First minute</option>
                    <option>Last minute</option>
                    <option>...</option>
                </select>
            </div>


            <div class="form-group">
                <label class="control-label">
                    Stravování &nbsp;&nbsp;&nbsp;
                </label>
                <label class="checkbox-inline"><input type="checkbox" value="">Snídaně</label>
                <label class="checkbox-inline"><input type="checkbox" value="">Obědy</label>
                <label class="checkbox-inline"><input type="checkbox" value="">Večeře</label>
            </div>


            <div class="form-group">
                <label class="control-label">
                    Ubytování
                </label>
                <select class="form-control">
                    <option>Hotel ****</option>
                    <option>Hotel ***</option>
                    <option>Motel</option>
                    <option>...</option>
                </select>
            </div>


            <div class="form-group">
                <label class="control-label">
                    Kapacita osob
                </label>
                <input class="form-control" type="number" value="10" min="20" />
            </div>

            <div class="form-group">
                <label class="control-label">
                    Datum začátku
                </label>
                <input type="date" class="form-control" value="2017-04-13" />
            </div>



            <div class="form-group">
                <label class="control-label">
                    Popis
                </label>
                <textarea class="form-control" rows="5" placeholder="Chtěli byste se podívat do Řecka? S námi můžete i s celou rodinou. Zájezd je..."></textarea>
            </div>


            <div class="form-group">
                <p>
                    <a class="btn btn-large ">
                        <span class="glyphicon glyphicon-paperclip" aria-hidden="true">
                        </span>&nbsp;Nahrát obrázky k zájezdu
                    </a>
                </p>
            </div>

            <div class="form-group">
                <p>
                    <a class="btn btn-danger btn-large pull-right">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true">
                        </span>&nbsp;Zrušit
                    </a>
                </p>
                <p>
                    <a class="btn btn-primary btn-large pull-right">
                        <span class="glyphicon glyphicon-ok" aria-hidden="true">
                        </span>&nbsp;Uložit
                    </a>
                </p>
            </div>


        </div>


    </div>
</div>

<hr>

ProjektMOIS/Views/Trip/Register.cshtml
@{
    ViewBag.Title = "Trip register";
}


<hr>
<h1>Rezervace k zájezdu</h1>

<div class="panel panel-success">
    <div class="panel-heading ">
        <div class="form-group">

            <h3><b>@ViewBag.Trip.Description<b></h3>
        </div>
        <div class="form-group">
            <label class="control-label">
                Cena
            </label>
            <p>@ViewBag.Trip.Prize,- Kč</p>
            <label class="control-label">
                Datum konání
            </label>
            <p>@ViewBag.Trip.DateStart - @ViewBag.Trip.DateEnd</p>
        </div>
    </div>

    <div class="panel-body">

        <div class="form-container">

            <div class="form-group">
                <label class="control-label">
                    Jméno a příjmení (zákazníka)
                </label>
                <input class="form-control" type="text" placeholder="Jan Novák" />
            </div>

            <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label">
                        Počet cestujících
                    </label>
                    <input class="form-control" type="number" value="4" min="0" />
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label">
                        z toho děti
                    </label>
                    <input class="form-control" type="number" value="1" min="0" />
                </div>
            </div>

            <!--
            <div class="form-group">
            <label class="control-label">Platba
            </label>
            <select class="form-control" >
                <option>Převodem</option>
                <option>Platební kartou</option>
                <option>Hotově na pobočce</option>
            </select>
            </div>
                -->




            <div class="form-group">
                <label class="control-label">
                    Poznámka k rezervaci
                </label>
                <textarea class="form-control" rows="5" placeholder="Rád bych se dozvěděl o..."></textarea>
            </div>


            <div class="form-group">
                <span class="label label-danger ">
                    Povrzení rezervace musí být učiněno na pobočce nejpozději do 25.4.2017, jinak rezervace propadá.
                </span>
            </div>

            <div class="form-group">
                <p>
                    <a class="btn btn-danger btn-large pull-right">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true">
                        </span>&nbsp;Zrušit
                    </a>
                </p>
                <p>
                    <a class="btn btn-primary btn-large pull-right">
                        <span class="glyphicon glyphicon-ok" aria-hidden="true">
                        </span>&nbsp;Uložit
                    </a>
                </p>
            </div>


        </div>


    </div>
</div>

<hr>